language: csharp
mono: none
dist: xenial
addons:
 snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
services:
 - docker
script:
 - sudo snap alias dotnet-sdk.dotnet dotnet
 - dotnet restore
 - dotnet build
global:
 - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
 - DOTNET_CLI_TELEMETRY_OPTOUT=1