version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0-alpine
    steps:
      - checkout
      - run: find .
      - run: dotnet new -i Peachpie.Templates::*
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Build.Tests
