name: CoreCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.2.20176.6
    - name: Install PeachPieTemplates
      run: dotnet new -i Peachpie.Templates::*
    - name: Build with dotnet
      run: dotnet build --configuration Release
